print("1. 자신의 이름, 나이, 주소, 연락처, 메일 주소를 출력해보자")
print('이재명')
print('31살')
print('남자')
print('zerobase@zerobase.com')
print('서울시 동작구')
print('크로스핏')
print("2. 내일 할 일을 화면에 출력해보자")
print('파이썬 4강')
print('자바 3강')
print('C언어 2강')
print('HTML 1강')
print("3. 지난주 지출약을 항목별로 화면에 출력해보자")
print('식사 : 6000원')
print("4. 오늘 가장 인상 깊었던 일을 출력해보자")
print('러닝 뒤질뻔')
print("5. 메신저를 이용해서 친구한테 전송할 메시지를 출력해보자")
print("미국 가자")